### ISSUE TITLE
[QST] Is there a way to retrieve/extract embeddings of users and movies once  DLRM model is trained ?

### ISSUE THREAD

**Issue by vijayendra-g** [NVIDIA-Merlin/models#1063]
# ❓ Questions & Help

## Details

I have just started exploring Merlin Models. Currently working with DLRM models
https://github.com/NVIDIA-Merlin/models/blob/main/examples/02-Merlin-Models-and-NVTabular-integration.ipynb

I wanted to check if there a way to retrieve/extract embeddings of users and movies once  DLRM model is trained ?

**Comment by vijayendra-g** [comment]
Any update on this ?

**Comment by rnyak** [comment]
@vijayendra-g we dont have a utility function for extracting item or user embeddings from a DLRM model. Since this is  a tf.keras model, then you should be able to extract the embedding layer of the trained model first,  and then take the embeddings of the user_id column, and item-id column wrt the column name in your train set.

- `model.layers[0].weights` should be giving you the embeddings in alphabetical order of feature names
- you can check out the embeddings with their feature name: `model.layers[0][0][0]['user_id']` as well.

hope that helps.

**Comment by rnyak** [comment]
@vijayendra-g I am closing this ticket due to low activity. Please reopen again if you have any further questions. thanks.
