### ISSUE TITLE
[Task] Example for using pre-trained embeddings

### ISSUE THREAD

**Issue by bschifferer** [NVIDIA-Merlin/models#421]
### Description
We want to add an example how to use pre-trained embeddings:

Multiple options
- pre-train item embeddings with word2vec/product2vec
- dataset with images and extract latent vector with pre-trained cnn model
- process text

**Additional context**
- related issues: https://github.com/NVIDIA-Merlin/Merlin/issues/211

**Comment by radekosmulski** [comment]
I am starting to believe I have been barking up the wrong proverbial tree on this one 🙂 

I left some new comments in [the doc](https://docs.google.com/document/d/1IqN1gH5zWvarK4CNo6Ngf-PlnuWDEmeffe7i0Zy09Hk/edit). I now believe this tutorial should be just a use case in Merlin models [here](https://github.com/NVIDIA-Merlin/models/tree/main/examples/usecases). It could just be a model trained with synthetic data emulating movie poster CNN descriptors.

The way I understand this is that the goal is to show the technical aspects of working with pretrained embeddings, that is the idea here. How to move them around, feed them to the model and accommodate them in the model. Getting the images from IMDB adds a lot of complexity to the pipeline and distracts from the main objectives (also, it is not clear to me that this use of embeddings can genuinely improve performance).

I will try to hack a proof of concept as I continue to get into Merlin models 🙂

One thought that comes to mind here is that we probably should aim to DRY up our examples. I don't think a full-blown tutorial using movielens would be a good direction here as we already have this covered in other places.

Separately, I have an idea for a nice tutorial where we could show how pretrained embeddings add value to the modeling, how they improve performance. I have been thinking about a word2vec model on the H&M data, but I am not sure if we are good to use that data, if we have the go-ahead (will check with @rnyak, I believe she might have a bit more information on the status of this).

I channeled my energy into the original approach I suggested on this and nearly got it to a working state, but as I keep learning more about our repos I don't think that was a good idea 🙂 But that's how it is, went down a less than ideal path but learned a lot along the way 🙂 

All this is tentative, would really appreciate your thoughts so that I could incorporate them into this work 🙂 Thank you! (I have a 1:1 with @bschifferer on Monday so that is an opportunity for me to pick his brains on this, but I know our broader example meeting got cancelled for this week, hence leaving this note here)

**Comment by rnyak** [comment]
@radekosmulski you can use H&M for pre-trained embedding example. You need to cite the Kaggle link, and users will download the dataset at their end. That's fine.

**Comment by radekosmulski** [comment]
Thank you very much @rnyak, so this is how it works! Wonderful to know! 🙂

I am still thinking of hacking together something simple on movielens and simulated image descriptors. This will be the simplest way for me to get more into Merlin Models and to demonstrate this technique (plus get feedback on the code that I write, I am sure there are bits of existing functionality I will miss).

But if we don't like the example, we don't have to use it.

I feel the example on H&M data could be genuinely interesting, will continue to work towards that 🙂

[Here](https://github.com/radekosmulski/NVTabular/tree/pretrained_embeddings_movielens/examples/pretrained-embeddings-movielens) is the code I started to put together using the old approach, but I don't think continuing this work would be useful.

**Comment by rnyak** [comment]
@radekosmulski I think you should not use the old code. You need to use keras layers, blocks, and dataloaders from Merlin Models. 
Also please look at [this TensorInitializer class](https://github.com/NVIDIA-Merlin/models/blob/main/merlin/models/tf/utils/tf_utils.py#L295) and also the unit tests particularly for `_pretrained_initializer` tests here: https://github.com/NVIDIA-Merlin/models/blob/main/tests/unit/tf/inputs/test_embedding.py 

This might give you an idea.
