### ISSUE TITLE
[QST] How does Merlin Models calculate top metrics?

### ISSUE THREAD

**Issue by future-xy** [NVIDIA-Merlin/models#546]
# The way Merlin Models calculates topk metrics seems strange

## Details

I'm reading the source code of Merlin Models but found that in topk.py, most, if not all, metric functions seem not even calculated based on the prediction.
Take recall_at as an example, ```y_pred```, the tensor corresponding to the prediction scores, seems not used at all. Instead, recall results are calculated based on ```y_true```, which is the tensor corresponding to true labels.
https://github.com/NVIDIA-Merlin/models/blob/d0ffe18d0bf94417fea523f8323487497838ded7/merlin/models/tf/metrics/topk.py#L49-L67

Do I misunderstand the meanings of y_pred and y_true or does y_true already contain the information of predictions?

Thanks for any hint.

**Comment by gabrielspmoreira** [comment]
Thanks for the question @future-xy . Those ranking metrics functions (`recall_at`, `ndcg_at`) expects that the both prediction scores (`y_pred`) and targets (`y_true`) were already sorted by the prediction scores (`y_pred`), which is done by `TopkMetric` if `pre_sorted=False`.
So to compute the ranking metrics you can just use the sorted targets (`y_true`), doing something as simple as [this](https://github.com/NVIDIA-Merlin/models/blob/d2bc6fe013e8651184dbb035222f8956c1b7e37b/merlin/models/tf/metrics/topk.py#L82) to compute the precision@k.
Some metrics functions like `recall_at()` also need the `label_relevant_counts` argument, which is a vector with how many relevant items each example has. All relevant items might not be available in the labels (`y_true`), because it might be already sorted and truncated to the top-k.
Does that answer your question?

**Comment by future-xy** [comment]
Thanks! that makes sense to me.
