### ISSUE TITLE
[FEA] Dressipi example using post-padding instead of pre-padding

### ISSUE THREAD

**Issue by zhiruiwang** [NVIDIA-Merlin/models#852]
# 🚀 Feature request
In example notebook [Dressipi session-based next item prediction](https://github.com/NVIDIA-Merlin/models/blob/main/examples/usecases/ecommerce-session-based-next-item-prediction-for-fashion.ipynb), in the preprocessing step it's using post-padding `nvt.ops.ListSlice(-SESSIONS_MAX_LENGTH, pad=True)` to contruct the sequence features, but pre-padding seems to make more sense for preprocessing session-based transaction data. I looked into the source code of `ListSlice` and found out that there is actually no pre-padding in the current implementation. There's an existing issue tracking this feature, but hasn't been updated for 5 month: https://github.com/NVIDIA-Merlin/NVTabular/issues/1552. 

With Merlin-models getting ready for sequential/session-based models, it's pretty crucial to pair it with Nvtabular to preprocess sequential data and feed into the models. I think pre-padding is way more common in sequential data preprocessing than post-padding, so it would be great if this issue can be prioritized to match with Merlin-models' awesome development. Thanks!

**Comment by rnyak** [comment]
@zhiruiwang thanks for reporting that. We will look into that, and get back to you.

**Comment by gabrielspmoreira** [comment]
Hi @zhiruiwang 
Merlin Models expects sequence features to not be padded. The reason is that Merlin Models makes usage of `tf.RaggedTensor` to represent sequences, which allow for having different sequence lengths for different examples.
So we should not use `nvt.ops.ListSlice(..., pad=True)` when preparing data to be used with Merlin Models.
@rnyak has already updated the Dressipi example in this [commit](https://github.com/NVIDIA-Merlin/models/commit/0352a2dd72c444b416cb1bfa2500022c4c08f0e3) to not use padding in `ListSlice`.
Does that address your FEA? Can we close this ticket?

**Comment by zhiruiwang** [comment]
Yes! I was looking into the new Dressipi notebook diff and was wondering why padding got removed. This explanation is very clear. We can close this ticket
