### ISSUE TITLE
[QST] Does XGBoost wrapper supports to feed data that excesses system memory?

### ISSUE THREAD

**Issue by bilzard** [NVIDIA-Merlin/models#959]
# ❓ Questions & Help

## Details

I'm reading source code of `merlin.models.xgb.XGBoost`. In my understanding, this is just a xgboost wrapper, and it seems to not supporting feeding data that excesses system memory. Is this correct?

And are there possibility to support this kind of feature?

**Comment by radekosmulski** [comment]
Hey @bilzard! Generally, since we use `xgb.dask.DaskDMatrix` and `xgb.dask.DaskDeviceQuantileDMatrix`, you should be able to train on data that is larger than your GPU RAM. But there is some limit to how big of a dataset you can use, regardless of how many GPUs you throw at the problem.

I don't fully understand how this works (doing some investigation at the moment) but somewhere along the training process (possibly once we have the histogram created encompassing all of the features) some portion of the data needs to still fit on a single GPU. There is a way to soften this requirement or possibly completely work around this, using [the Iterator approach](https://xgboost.readthedocs.io/en/stable/tutorials/external_memory.html), but we don't currently support this method of feeding the data to your model and I am not completely sure to what extent this would address the problem.

But, since under the hood, we use `xgb.dask.DaskDeviceQuantileDMatrix` for training, this should still allow you to train on quite a bit of data (it uses a more efficient representation of data than the standard `DMatrix` approach), we are probably talking about millions of rows.

So yes, unfortunately, the situation is not very clear, but in general running on data larger than your GPU RAM should not be a problem. Beyond a certain point, which is probably quite far out there in terms of size of your data, you will likely encounter a situation were you will not be able to train the model, so there is some limit in terms of the size of the data. And for the system memory (CPU RAM) that you are asking about, using the cuda cluster that is provided out of the box with Merlin Models should help, dask should help manage that for you, so while there will be a limit to what data you can fit using your hardware, reducing memory consumption via casting to smaller dtypes and using the xgboost from our library are the two best bets that come to my mind (since a bunch of stuff should be automatically handled for you in the background).

This is the best answer I can give today, but thank you for raising this, this is certainly of interest. Let me see if we can address this down the road via a closer look at how memory is managed and what we can do once we move to really large datasets.

**Comment by bilzard** [comment]
@radekosmulski Thank you for detailed reply.

So, actually, I have tried to train a large (~8M rows) dataset with NVTabular but failed with OOM error. I once issued a bug report[^1] on NVTabular's GitHub repository, but close it because I'm not sure this is officially supported function.

So, if using `xgb.dask.DaskDMatrix` or `xgb.dask.DaskDeviceQuantileDMatrix`, it allows to feed dataset excess with actual GPU memory, right?
If it is, where should I cast this issue?

[^1]: https://github.com/NVIDIA-Merlin/NVTabular/issues/1750

**Comment by rjzamora** [comment]
You are correct that `merlin.models.xgb.XGBoost` is a thin wrapper around `xgb.dask`. Therefore, you will probably get the most feedback/feedback if you file an issue in https://github.com/dmlc/xgboost.

With that said, I can see in the `xgb.dask` code that the initialization of a `DaskDMatrix` object calls `persist` on the input dataset, and then uses [client.scheduler.who_has](https://github.com/dmlc/xgboost/blob/16ef016ba7d9f9d2ed6d0888933417e38f5ebc7b/python-package/xgboost/dask.py#L457) to figure out exactly which Dask-Array chunks have been assigned to each worker in the Dask cluster.  The practice of calling `persist` like this effectively forces the Dask cluster to try to read all data into global memory at once.

If the cluster is using Dask-CUDA workers (with spilling), the `persist` call alone will not cause an OOM error. However, the actual `fit` logic may also be assuming that the full dataset will in fit in distributed memory.  If so, it's probably possible to adapt the code to handle larger-than-distributed-memory data, but it may require significant work.

**Comment by bilzard** [comment]
> You are correct that merlin.models.xgb.XGBoost is a thin wrapper around xgb.dask

Thank you for confirmation. and also the explanation of `dask_client`'s source code.

Since I have little knowledge of how dask / dask_duda works, I tied to study them more.

Anyway, if the responsibility of GPU memory management is outside of this repository, I will closing this issue.
